version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: oboticario
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  backend:
    container_name: backend
    image: williamp/backend-test:latest
    restart: on-failure:5
    ports:
      - 3333:3333
    depends_on:
      - db
