version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: oboticario
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  backend:
    container_name: backend
    image: node:12
    restart: on-failure:5
    command: ['tail', '-f', '/dev/null']
    ports:
      - 3333:3333
    working_dir: /backend
    volumes:
      - ./:/backend
    depends_on:
      - db
